### ISSUE TITLE
Turn off the Raspberry

### ISSUE THREAD

**Issue by Artsonic** [climberhunt/LapsePiTouch#3]
Hi, is there a way to add a power off button on the main interface ?

The only way i can power off the raspberry once LapsePitouch is runing is by removing the power cable wich corrupt files ....

Thanks.

**Comment by Artsonic** [comment]
I added the quit button and a nicer UX in my fork.

Regards.

**Comment by climberhunt** [comment]
Nice job on the GUI!
For shutting down safely, I use a tactile button soldered onto the leftmost switch position and  the driver mentioned here: https://learn.adafruit.com/adafruit-pitft-28-inch-resistive-touchscreen-display-raspberry-pi/extras

**Comment by Artsonic** [comment]
Oh ok, didn't realize that. I might try that to then ...

I also added a button to go back to the desktop, and a shortcut on the desktop to start LapsePi.
